### ISSUE TITLE
Enterprise Labs

### ISSUE THREAD

**Issue by gmspinheiro** [gmspinheiro/SEBC#3]

**Comment by rafaelarana** [comment]
Good. 


Comments about 0_CM_treasure_hunt.md

How do you upgrade the CM agents? It's also common in some customers to upgrade agents direectly via yum (no only via CM)

What steps must be completed before integrating Cloudera Manager with Kerberos?Download and deploy jce if using AES256 and jdk < 8 
FALSE - JCE is required  if Java version  < Java 8u162 (See https://bugs.openjdk.java.net/browse/JDK-8170157)
